### ISSUE TITLE
Where to find/download SRA design matrix and config.json file information

### ISSUE THREAD

**Issue by sherfey1** [pachterlab/bears_analyses#11]
Hello, 

I am looking to find SRA design matrix and config.json file information for the 6 runs of Study SRP014759 on SRA website. The paper introducing the Lair, by Pimentel et al., says that design matrix can be found from the SRA, but I am not sure where to look. 

Thanks.

**Comment by psturmfels** [comment]
It is located at the "RunInfo Table" button here: http://www.ncbi.nlm.nih.gov/Traces/study/?acc=SRP014759

As for the config.json file, you'll have to create this yourself based on the specifications in the paper.
