### ISSUE TITLE
ABA Is Required for Plant Acclimation to a Combination of Salt and Heat Stress

### ISSUE THREAD

**Issue by pimentel** [pachterlab/bears_analyses#2]
http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0147625

**Comment by psturmfels** [comment]
http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0136765

**Comment by psturmfels** [comment]
http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE72806
It seems as though this data is not currently available.
